### ISSUE TITLE
Problem to pull files

### ISSUE THREAD

**Issue by cloatre** [rpp0/gr-lora-samples#1]
Hello,
# I try to retrieve the lora sample but it fails, how can I do?

$ git lfs clone https://github.com/rpp0/gr-lora-samples.git
Clonage dans 'gr-lora-samples'...
remote: Counting objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Dépaquetage des objets: 100% (22/22), fait.
Vérification de la connectivité... fait.
Git LFS: (0 of 14 files) 0 B / 1.92 GB  
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
# 

Thanks,

**Comment by rpp0** [comment]
Looks like I'm getting too much traffic for the free Github plan. I've uploaded the samples to my research page as an alternative: http://research.edm.uhasselt.be/~probyns/lora/gr-lora-samples.zip
