### ISSUE TITLE
Please upload ACTUAL 2Gigs of gr-lora-samples to https://github.com/rpp0/gr-lora-samples because "Pointer file displayed on GitHub instead of actual file"

### ISSUE THREAD

**Issue by WindyCitySDR** [rpp0/gr-lora-samples#2]
Hello,

Users of your **https://github.com/rpp0/gr-lora** wont be able to successfully run _./lora_receive_file.py_ becaude the **https://github.com/rpp0/gr-lora-samples** files stored by git-lfs are displayed as pointers **(instead of the actual file)**. 

:-(

An example of file is https://github.com/rpp0/gr-lora-samples/blob/master/00000000_crcoff_cr4_sf7.cfile showing up as

 **4 lines (3 sloc) 102 MB
version https://git-lfs.github.com/spec/v1
oid sha256:5733ebff56d9ea0d97387cdd2b7c95ea21de9014383b92acdc91fa9b0fec8574
size 106970312**

:-(

....meanwhile in the full commit listing (**github.com/rpp0/gr-lora-samples@52ed06d**) 
this file is actually listed as "Git LFS file not shown".   

:-(

I believe, but may be wrong, that the issue your **https://github.com/rpp0/gr-lora** is suffering from is as follows:

**Pointer file displayed on GitHub instead of actual file #1056**
[https://github.com/github/git-lfs/issues/1056](url)

.... which makes reference to this:

**Fix `git rev-list` when a file exists with the same name as the branch #1096**
[https://github.com/github/git-lfs/pull/1096](url)

Can you fix this please and/or upload the sample files to another location where the public can download **gr-lora sample files** to utilize ./lora_receive_file.py ?  This would be for those of us WITHOUT Lora Hardware to generate our own sample files,

**Comment by rpp0** [comment]
Hi,

Github requires the use of LFS for large files; it's not possible to upload them directly. You can download the files using `git lfs pull`. However, since the repository appears to be popular I am over my quota. I have uploaded the samples to my research page for your convenience: http://research.edm.uhasselt.be/~probyns/lora/gr-lora-samples.zip

**Comment by WindyCitySDR** [comment]
rpp0m


Thank you for uploading the gr-lora-samples.zip file and your gr-lora work
as this is truly cool indeed!

Outstanding of you to reply.

**Comment by WindyCitySDR** [comment]
rpp0m

Thank you for uploading the gr-lora-samples.zip file and your gr-lora work
as this is truly cool indeed!

Outstanding of you to reply and this is now resolved!

Thank you!
